version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - spring-boot-prometheus
  prometheusapplication:
    image: prometheusapplication
    container_name: prometheusapplicationContainer
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - "8080:8080"
    networks:
      - spring-boot-prometheus

networks:
  spring-boot-prometheus: